# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozpcenter', '0030_recommendationfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='feedback_score',
            field=models.IntegerField(default=0),
        ),
    ]
