# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozpcenter', '0031_notification_notification_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='feedback_score',
            field=models.IntegerField(default=0),
        ),
    ]
