# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozpcenter', '0034_auto_20171113_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
