# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozpcenter', '0035_auto_20171221_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
