# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozpcenter', '0038_auto_20180221_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_508_compliant',
            field=models.BooleanField(default=False),
        ),
    ]
