# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-30 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozpcenter', '0039_listing_is_508_compliant'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='only_508_search_flag',
            field=models.BooleanField(default=False),
        ),
    ]
