# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-11 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozpcenter', '0041_listingvisitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
