# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-22 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ozpcenter', '0043_work_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_avatar', to='ozpcenter.Image'),
        ),
    ]
