# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-12 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ozpcenter.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ozpcenter', '0043_work_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=ozpcenter.utils.get_now_utc)),
                ('modified_date', models.DateTimeField(default=ozpcenter.utils.get_now_utc)),
                ('is_root', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('FOLDER', 'FOLDER'), ('LISTING', 'LISTING')], default='FOLDER', max_length=255)),
                ('bookmark_parent', models.ManyToManyField(db_table='bookmark_parents', to='ozpcenter.BookmarkEntry')),
                ('creator_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozpcenter.Profile')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_entries', to='ozpcenter.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=ozpcenter.utils.get_now_utc)),
                ('modified_date', models.DateTimeField(default=ozpcenter.utils.get_now_utc)),
                ('user_type', models.CharField(choices=[('OWNER', 'OWNER'), ('VIEWER', 'VIEWER')], default='VIEWER', max_length=255)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_permission', to='ozpcenter.BookmarkEntry')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozpcenter.Profile')),
            ],
        ),
        migrations.AddIndex(
            model_name='bookmarkpermission',
            index=models.Index(fields=['bookmark', 'profile'], name='ozpcenter_b_bookmar_bca0d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmarkpermission',
            unique_together=set([('bookmark', 'profile')]),
        ),
    ]
