# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-25 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozpcenter', '0044_auto_20180612_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkentry',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
