# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-06 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ozpcenter', '0044_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontCustomization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('FEATURED', 'FEATURED'), ('RECOMMENDED', 'RECOMMENDED'), ('RECENTLY_ADDED', 'RECENTLY_ADDED'), ('MOST_POPULAR', 'MOST_POPULAR'), ('FREQUENTLY_VISITED', 'FREQUENTLY_VISITED'), ('UPDATES', 'UPDATES'), ('MY_LISTINGS', 'MY_LISTINGS')], max_length=50)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_customizations', to='ozpcenter.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='storefrontcustomization',
            unique_together=set([('profile', 'section')]),
        ),
    ]
