---
- name: Install prereqs
  yum: name={{ item }} state=present
  with_items:
    - pcre
    - pcre-devel
  become: true

- name: Create haproxy user
  user:
    name: haproxy
    comment: "haproxy"
    # group: haproxy
    password: "password"
  become: true

- name: Create /src directory
  command: mkdir -p /src
  become: true

- name: Download HAProxy source
  when: not offline
  get_url:
    url: http://www.haproxy.org/download/1.6/src/haproxy-1.6.3.tar.gz
    dest: /src/haproxy-1.6.3.tar.gz
  become: true

- name: Extract archive
  unarchive:
    src: /src/haproxy-1.6.3.tar.gz
    dest: /src
    copy: no
  become: true

- name: Make haproxy
  command: chdir=/src/haproxy-1.6.3 make TARGET=linux2628 CPU=x86_64 USE_OPENSSL=1 USE_ZLIB=1 USE_PCRE=1
  become: true

- name: Install haproxy
  command: chdir=/src/haproxy-1.6.3 make install
  become: true

- name: Copy binaries
  shell: cp -f /usr/local/sbin/haproxy /usr/sbin/
  become: true

- name: Copy init.d script
  command: cp /src/haproxy-1.6.3/examples/haproxy.init /etc/init.d/haproxy
  become: true

- name: Fix permissions on init.d script
  command: chmod +x /etc/init.d/haproxy
  become: true

- name: Create directory for config file
  command: mkdir -p /etc/haproxy
  become: true

- name: Copy haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    # group: root
    mode: 0644
  become: true

- name: Create status file
  shell: mkdir -p /var/lib/haproxy;touch /var/lib/haproxy/stats
  become: true

- name: Create directory for socket file
  command: mkdir -p /var/run/haproxy
  become: true

- name: Copy cert
  copy:
    src: ../files/
    dest:  /etc/ssl/certs/
    owner: haproxy
    force: yes
  become: true

- name: Ensure haproxy is running (and enable it at boot)
  service: name=haproxy state=restarted enabled=yes
  become: true
