---
redis_version: 3.2.1
## Installation options
redis_install_dir: /opt/redis
redis_user: redis
redis_group: "{{ redis_user }}"
redis_dir: /var/lib/redis/{{ redis_port }}
redis_download_url: "http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz"
redis_tarball: false
# The open file limit for Redis/Sentinel
redis_nofile_limit: 16384

# #####################
# redis.config
# #####################

##### NETWORK ######
redis_protected_mode: "no"

redis_tcp_backlog: 511
redis_network_timeout: 0
redis_tcp_keepalive: 300

###### GENERAL #######
redis_daemonize: "yes"
redis_supervised: "no"

redis_pidfile: /var/run/redis/{{ redis_port }}.pid
redis_loglevel: notice

## Logging
redis_logfile: /var/log/redis/redis-server.log
# Enable syslog. "yes" or "no"
redis_syslog_enabled: "no"
redis_syslog_ident: redis_{{ redis_port }}
# Syslog facility. Must be USER or LOCAL0-LOCAL7
redis_syslog_facility: USER

# Number of databases to allow
redis_databases: 16

###### SNAPSHOTTING ######

# How frequently to snapshot the database to disk
# e.g. "900 1" => 900 seconds if at least 1 key changed
redis_save:
  - 900 1
  - 300 10
  - 60 10000

redis_stop_writes_on_bgsave_error: "yes"
redis_rdbcompression: "yes"
redis_rdbchecksum: "yes"
redis_dbfilename: dump.rdb

###### REPLICATION #######
# No Modifications

###### SECURITY ######

redis_rename_config:
  - CONFIG CONFIG_OZP
  - FLUSHDB FLUSHDB_OZP
  - FLUSHALL FLUSHALL_OZP
  - DEBUG DEBUG_OZP
  - SHUTDOWN SHUTDOWN_OZP

###### LIMITS ######
redis_maxclients: 10000
# 4000000000 bytes is 4gb
# redis_maxmemory: 4000000000
# redis_maxmemory_policy: noeviction

###### APPEND ONLY MODE ######
redis_appendonly: "no"
redis_appendfilename: appendonly.aof

redis_appendfsync: "everysec"
redis_no_appendfsync_on_rewrite: "no"
redis_auto_aof_rewrite_percentage: "100"
redis_auto_aof_rewrite_min_size: "64mb"

###### SLOW LOG ######
# Log queries slower than this many milliseconds. -1 to disable
redis_slowlog_log_slower_than: 10000
# Maximum number of slow queries to save
redis_slowlog_max_len: 128
